### ISSUE TITLE
회원가입, 로그인에 사용할 보안 기술 관련 (Spring Security, OAuth2.0, JWT)

### ISSUE THREAD

**Issue by 5hk5** [do88y/nDaysChallenge#12]
## 주제  
회원가입, 로그인 (일반/소셜) 기능에 사용할 보안(인증/인가) 기술 선택

## 정보
Spring Security : 사용자 인증, 접근 권한 부여 담당하는 프레임워크
OAuth2 : 구글, 카카오 등 타 서비스에서 정보를 가져올 권한을 위임하는 프레임워크
JWT : JSON 객체를 사용해 데이터를 저장하고 안전하게 전달하는 토큰

### 기술 조합 종류 (아래 조합 외에도 적용할 기술 또는 기술조합 있을 시 의견 제시 부탁드립니다)

  + JWT & OAuth2
  + Spring Security & OAuth2
  + Spring Security & JWT
  + Spring Security & JWT & OAuth2

각 기술의 장단점과 최적의 조합에 대해 코멘트 나눠봐요!! 😄

**Comment by do88y** [comment]
###스프링 시큐리티
- 스프링 기반 시스템과 통합성이 좋음
- 로직을 직접 작성하지 않아도 됨
