### ISSUE TITLE
템플릿 상세내용 수정 완료

### ISSUE THREAD

**Issue by do88y** [do88y/nDaysChallenge#13]
### ✔체크 리스트 (이슈 올리기 전 아래 내용을 확인해 주세요)
- 적절한 라벨과 Assignees를 지정해 주세요
- 논의가 끝난 이슈은 작성자가 완료처리를 해주세요

### ✍이슈 내용
깃허브 템플릿 상세 내용 수정했습니다.
내용을 동일하게 가져갈 수 있을 것 같아서 기존에 세 파트로 나누었던 것은 그대로 두었고
작성 시에 적절한 라벨과 Assignees 지정 해 주시면 될 것 같은데 한 번 확인 해 보시고 피드백 주세요!

**Comment by 5hk5** [comment]
넵 확인했습니다~!
