### ISSUE TITLE
챌린지 만들기 횟수 제한을 없앨

### ISSUE THREAD

**Issue by do88y** [do88y/nDaysChallenge#23]
### ✔체크 리스트 (이슈 올리기 전 아래 내용을 확인해 주세요)
- 적절한 라벨과 Assignees를 지정해 주세요
- 논의가 끝난 이슈은 작성자가 완료처리를 해주세요

### ✍이슈 내용

외람된 말씀이오나...
혹시 챌린지 개인당 5개 제한을 없앨 수 있을까요..?
다음 버전때 넣거나 하더라도... 이것 때문에 머리가 터질 것 같습니다..

단체인 경우가 문제인데
1. 챌린지 만든 사람을 특정해야 함
2. 그 특정한 사람만 만들고 지울 때 챌린지 count 값을 바꿔줘야 함
3. 챌린지를 만들 때 값이 바뀌는데 컬럼이 Room 에 있지 않기 때문에 RoomMember를 참조해야 함
4. 하지만 RoomMember에는 챌린지가 만들어진 이후에 값이 들어감(..?!)
5. RoomMember를 Room이 상속받아 Room 생성자에 RoomMember 생성자를 끼워넣음
6. 생성자를 builder 패턴으로 만들었는데 builder패턴 레퍼런스 찾기가 힘듦...
7. Room에도 count를 넣어서 cascade설정할까 고민 하다가 이건 아니다 싶어서 글을 씁니다...

**Comment by wonsy1006** [comment]
프론트는 개수 제한 없어도 좋습니다!!

**Comment by wonsy1006** [comment]
혹은 지금은 개인 챌린지만 제한 두고 단체는 일단 그냥 두는 것이 어떨까요
단체는 어차피 2인 이상이어야 만들 수 있으니까 막 여러 개 만드는 사람이 있을 것 같지는 않은데
개인이 제한 없이 무한으로 만들어서 관리하기 어려워 지는 게 문제라면 개인 챌린지 5개 제한 두고 단체는 그냥 알아서 하기 ?ㅋㅋ 도 괜찮을 것 같습니다

**Comment by 5hk5** [comment]
전 count 필드가 방장한테만이 아닌 모든 멤버에게 주어지는 걸로 파악했었습니당.. count가 5 넘어가는 회원 누구나 방 생성 못 하도록 버튼을 숨기고, Member 클래스에 방장 여부 확인하는 필드 추가해서 방장에게만 챌린지 삭제 권한 주는 게 어떨까요..?? 그렇게 해서 방장이 방을 삭제하면 소속 멤버들 count 숫자도 하나씩 줄게 하구요.. 저도 한번 구현 방식 같이 생각해보겠습니다 구현 어려울 시 우선 개인부터 하는 의견에는 동의합니다!

**Comment by do88y** [comment]
그렇다면 난이도가 조금 낮아질 것 같아서 다시 한 번 도전 해보겠습니다~! 감사합니다 선생님들👍
