### ISSUE TITLE
연관관계 주인 정하는 것 관련 여러분의 의견이 필요합니다.

### ISSUE THREAD

**Issue by do88y** [do88y/nDaysChallenge#33]
### ✔체크 리스트 (이슈 올리기 전 아래 내용을 확인해 주세요)
- 적절한 라벨과 Assignees를 지정해 주세요
- 논의가 끝난 이슈은 작성자가 완료처리를 해주세요

### ✍이슈 내용
우리 챌린지에 속한 멤버 조회하는 것 보다
멤버가 속한 챌린지 검색하는게 많을 것 같은데 맞을까요..?
OneToOne 연관관계 주인 정하는 것 관련해서 여러분의 도움을 받고 싶습니다~!

**Comment by 5hk5** [comment]
네 저도 챌린지 상세화면 조회할 때 Room 테이블 데이터를 더 많이 사용할 것 같아서 Member을 연관관계 주인으로 하는 게 좋을 것 같습니다
