### ISSUE TITLE
룸컨트롤러 코드리뷰

### ISSUE THREAD

**Issue by do88y** [do88y/nDaysChallenge#60]
### ✔체크 리스트 (PR 올리기 전 아래 내용을 확인해 주세요)
- merge 할 브랜치의 위치를 확인해 주세요 (master/main❌)
- 적절한 라벨과 Assignees를 지정해 주세요
- 리뷰가 필요한 경우 '리뷰' 라벨을 달아주고, 리뷰어를 지정해 주세요
- 승인된 PR은 리뷰어가 머지를 하고, 수정 요청이 온 경우 수정 후 다시 push 를 합니다.

### ✍PR 내용
RoomController 초안 작성했는데 여유있을 때 리뷰 부탁합니다!

**Comment by 5hk5** [comment]
매핑 주소에 {user} 삭제하신 후에 UserDetailsImpl 객체로 사용자 정보 얻어오시면 될 것 같습니다!
그리고 dto들 보면 커스텀 객체로 받아오는데, 뷰에선 다 숫자나 문자열로 구성된 데이터를 받아오는 거니까 String이나 Long, int로 받아온 후 컨트롤러나 서비스 단에서 해당 객체로 변환시켜야 할 것 같아요
